### ISSUE TITLE
Allow user to choose ECI mode directly

### ISSUE THREAD

**Issue by lt623tl** [woo-j/OkapiBarcode#100]
when i use Chinese to generate qrcode,always use SJIS charset
![image](https://github.com/woo-j/OkapiBarcode/assets/108046011/71dfa82d-33d4-4d1c-a3c8-c1662f494daa)
and always reset in qrcode 
![image](https://github.com/woo-j/OkapiBarcode/assets/108046011/dbd57582-0a1a-4565-92e7-c3da6c3dba9e)
can you support direct to set  eciMode

**Comment by gredler** [comment]
I don't think I fully understand your issue. Can you provide more details? Sample data, observed output, and expected output would be great. Thanks!

**Comment by lt623tl** [comment]
when i use "中文" in qrcode inputData, eciMode always 20, so inputData always reencode  ,i hope  direct set  eciMode

**Comment by gredler** [comment]
But the resultant QR Code is encoded correctly, and then decodes correctly to "中文" on a scanner, right? I still don't understand the need to control the ECI directly if the auto-selected ECI results in correct encode / decode.

**Comment by gredler** [comment]
Closing, feel free to reopen with more information about the expected benefits of being able to manually set the ECI mode, if you still think this is a valuable enhancement.
