### ISSUE TITLE
`PDF417#setStructuredAppendFileId` limit

### ISSUE THREAD

**Issue by uwolfer** [woo-j/OkapiBarcode#102]
Currently, you limit `PDF417#setStructuredAppendFileId` between 0 and 900.

I have not found any specs which says anything about this field and limits, but I can see in my J4L implementation, that the following is assigned, and readers are also able to get that number out of it.

```java
new int[] {
  (int) (Math.random () * 255),
  (int) (Math.random () * 255),
  (int) (Math.random () * 255),
  (int) (Math.random () * 255)
};
```

The impl handles it like this:
```java
for(h = 0; h < this.PDFMacroFileId.length; ++h) {
  tmpBlock[tmpBlockCount++] = this.PDFMacroFileId[h];
}
```

Do you remember why you have used the 900 max? Do you think we can extend this to also allow bigger numbers?

**Comment by gredler** [comment]
To simplify the implementation. From the spec:

> For each related Macro PDF417 symbol, the file ID field contains the same value. This ensures that all re-
assembled symbol data belongs to the same distributed file representation. The file ID is a variable length
field which begins with the first codeword following the segment index and extends to the start of the optional
fields (if present) or to the end of the Control Block (if not).

> Each codeword in the file ID can have a value between 0 and 899, effectively making the file ID a series of
base 900 numbers. Each codeword of the series is transmitted as the 3-digit ASCII representation of its
decimal value.

By limiting the value to between 0 and 899, we use only one codeword and do not have to perform any base-900 conversion.

**Comment by uwolfer** [comment]
> By limiting the value to between 0 and 899, we use only one codeword and do not have to perform any base-900 conversion.

I see. So changing `StructuredAppendFileId` from `int` to `int[]` and limiting each item to a value to between 0 and 899 would be possible?

Background: [Swiss tax specs](https://www.ech.ch/sites/default/files/dosvers/beilagen/BEIL2_d_DEF_2022-06-07_eCH-0196_V2.0.0_Barcode%20Generierung%20-%20Technische%20Wegleitung.pdf) (page 6, 2nd last paragraph) say the following (translated by me):
> A random number (4 integers) is stored in the PDFMacroFileId attribute for unique identification during scanning.

I do not think this is very specific, but a number between 0 and 899 does in my understanding not fulfill this requirement.

**Comment by gredler** [comment]
The PDF417 spec seems to allow an arbitrary number of base-900 codewords, but it sounds like the tax spec requires 4 for some reason? If we were to change this, we would probably make it a `long` (instead of an `int`) and limit the value to under 900^4 and take care internally of doing the base-900 conversion (instead of forcing users to do it). But we don't want to waste codewords (possibly unnecessarily forcing a larger symbol size), so the code would have to add one codeword if the value is under 900, two codewords if the value is under 900^2, etc.

**Comment by uwolfer** [comment]
I would also be fine with this long based approach. But I see also advantages of adding an overloaded int array method which makes it probably a bit more visible that something "special" is happening under the hood, and it would also allow more flexibility with regards to the length.
