### ISSUE TITLE
a typing error in setupBitGrid of MicroQrCode?

### ISSUE THREAD

**Issue by Jonney3099** [woo-j/OkapiBarcode#15]
OkapiBarcode-master\src\main\java\uk\org\okapibarcode\backend\MicroQrCode.java

on Last rung in setupBitGrid:
grid[(8 * size) + 8] += 20;

Should be grid[(8 * size) + 8] += 0x20;

I am not quite sure because I haven't tested.

**Comment by woo-j** [comment]
Hi Jonney3099,

Thank you for spotting this, I will fix it shortly.

Robin.
