### ISSUE TITLE
Compute MicroQRCode binary_count() in getBinaryLength

### ISSUE THREAD

**Issue by Jonney3099** [woo-j/OkapiBarcode#16]
In getBinaryLength,  Should we  count length of Terminator and encoded String binary and Mode indicators???

Table 2 —Mode indicators for QR Code 2005
  Mode                     QR Code symbols       Micro QR Code symbols
  ----                     ---------------       ---------------------------
  Version                       all              M1       M2      M3      M4
  Mode indicator length
      (bits)                    4                  0       1       2       3
  ECI                          0111             n/a     n/a     n/a     n/a
  Numeric                      0001             n/a      0       00     000
  Alphanumeric                 0010             n/a      1       01     001
'  Byte                         0100             n/a     n/a      10     010
'  Kanji                        1000             n/a     n/a      11     011
  Structured Append            0011             n/a     n/a     n/a     n/a
     FNC1
                               0101 (1st        n/a     n/a     n/a     n/a
                              position)
                               1001 (2nd
                              position)

 Terminator
 (End of Message)             0000              000    00000  0000000 000000000

private void getBinaryLength() {
        int i;

        for (i = 0; i < 4; i++) {
            binary_count[i] = 0;
        }

        i = 0;
        do {
            if ((binary.charAt(i) == '0') || (binary.charAt(i) == '1')) {
                binary_count[0]++;
                binary_count[1]++;
                binary_count[2]++;
                binary_count[3]++;
                i++;
            } else {
                switch (binary.charAt(i)) {
                case 'K':
                    binary_count[0] += 3;
                    binary_count[1] += 5;
                    binary_count[2] += 7 + 2;
                    binary_count[3] += 9 + 3;
                    i += 2;
                    break;
                case 'B':
                    binary_count[0] += 3;
                    binary_count[1] += 5;
                    binary_count[2] += 7 + 2;
                    binary_count[3] += 9 + 3;
                    i += 2;
                    break;
                case 'A':
                    binary_count[0] += 3;
                    binary_count[1] += 5 + 1;
                    binary_count[2] += 7 + 2;
                    binary_count[3] += 9 + 3;
                   i += 2;
                    break;
                case 'N':
                    binary_count[0] += 3;
                    binary_count[1] += 5 + 1;
                    binary_count[2] += 7 + 2;
                    binary_count[3] += 9 + 3;
                     i += 2;
                    break;
                }
            }
        } while (i < binary.length());
    }

**Comment by woo-j** [comment]
The length of mode indicators and character count indicators are calculated correctly: for example for Numeric mode (case 'N') in M2 (binary_count[1]) add 5 bits (1 bit mode indicator, 4 bits count). Calculating for invalid options like Kanji mode for an M1 symbol makes no sense and these values would be ignored anyway.

I will have to do some research to confirm the situation with the terminator, however.

**Comment by Jonney3099** [comment]
Refer to ISO/IEC 18004 2006 Page 97 Micro qr Code example, the input string is "01234567", they recommend to use Version: M2 and ECC Level: L. But zint/OkapiBarcode slighly differ to use Version: M2 and ECC Level: M. Where is the difference coming from? I investigated and found getBinaryLength produce the variance. Because getBinaryLength only consider bits of character count indicator + Mode indicator length, they didn't consider length of Terminator. If we consider Terminator then we will get the same final MicroQRCode picture. I don't know which is perfect right.

**Comment by woo-j** [comment]
It's taken me a while to understand what is happening here, but you are right the count needs to add the length of the terminator if there are less than 4 bits left in the symbol (see section 6.4.9). The code was handling the terminator completely wrong. I have corrected this and I have taken the opportunity to tidy up the way the code works so that it no longer creates an intermediate binary string for Micro QR, but creates all of the binary in one function. it now generates the test symbol from figure I.4 (on page 97) correctly.
