### ISSUE TITLE
A hidden bug in QRCode encode function?

### ISSUE THREAD

**Issue by Jonney3099** [woo-j/OkapiBarcode#17]
Look like est_binlen is bit but qr_data_codewords_M[version - 1] is word (8 bits). I think we need multiply 8,otherwise, we can't get right ecc_level. 

public boolean encode() {

/...
       * Ensure maxium error correction capacity */
        if (est_binlen <= qr_data_codewords_M[version - 1]) {
            ecc_level = EccMode.M;
        }
        if (est_binlen <= qr_data_codewords_Q[version - 1]) {
            ecc_level = EccMode.Q;
        }
        if (est_binlen <= qr_data_codewords_H[version - 1]) {
            ecc_level = EccMode.H;
        }
/...

**Comment by woo-j** [comment]
You are right, I'll patch this now. Thank you.

Robin.
