### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by marcheschi** [woo-j/OkapiBarcode#23]
Hi 
I tried to compile it on my PC (illumos unix)
I got this error:
BUILD FAILED

Total time: 4.73 secs
Stopped 0 compiler daemon(s).
bash-4.2$ ./gradlew --stacktrace jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava/zpoolData/home/Paolo/Downloads/OKAPI/OkapiBarcode-master/src/test/java/uk/org/okapibarcode/backend/SymbolTest.java:433: error: cannot find symbol
        Class< ? > paramType = setter.getParameters()[0].getType();
                                     ^
  symbol:   method getParameters()
  location: variable setter of type Method
1 error
 FAILED
Can you help ?

Paolo

**Comment by woo-j** [comment]
Hi Paolo,

I'm not familiar with that section of code, as I didn't write it, but I think line 433 of SymbolTest.java should read:

Class< ? > paramType = setter.getParameterTypes()[0];

I suspect the real problem here, though, is that you probably don't need to be compiling the test libraries. I will have a look at the gradle options.

Robin.

**Comment by woo-j** [comment]
Hi again Paolo,

I am not familiar with gradle, but I have found a work around which you can use to get the project built and run:

Open up the file 'build.gradle' and comment out lines 15, 16, 17 and 26...

```
//testCompile 'junit:junit:4.12'gr
//testCompile 'com.google.zxing:javase:3.2.1'
//testCompile 'org.reflections:reflections:0.9.9'
//dependsOn 'check'
```

Then add the following two lines to the file:

```
apply plugin: 'application'

mainClassName = 'uk.org.okapibarcode.OkapiBarcode'
```

You should then be able to build and run Okapi with

```
./gradlew jar
./gradlew run
```

Robin.

**Comment by gredler** [comment]
It looks like this test class uses a Java 8 method, but our build file claims that we can compile against Java 7. We should be able to update the line in SymbolTest that reads:

Class< ? > paramType = setter.getParameters()[0].getType();

to the following (to make it compatible with Java 7):

Class< ? > paramType = setter.getParameterTypes()[0];

**Comment by marcheschi** [comment]
Hi
Thank you
removing the tesctcompile session , made the magic, now it works.
Thank you

I tried also the solution by gredler, and it moves forward but ends with a build failure .

Thank  you for the replies.

Paolo

**Comment by gredler** [comment]
Hi Paolo,

What build failure did you see? Can you send some details? Things build fine on JDK7 for me with the code tweak outlined above.

Thanks!

**Comment by gredler** [comment]
Never mind -- I see now that some of the recent QR code optimizations have broken the QR code test expectations.

**Comment by gredler** [comment]
Hoping to set up a Travis CI build this week that will build against Java 7. Once that's done and we've verified that the build passes, I'll close this issue.

**Comment by gredler** [comment]
Haven't been able to get a build going on Travis CI for this official repo yet, but I do have one up and running on my own fork, and all the tests are passing:

https://travis-ci.org/gredler/OkapiBarcode

@marcheschi can you verify that the latest code builds on your system?

**Comment by gredler** [comment]
Official Travis CI build now up and running (and passing):

https://travis-ci.org/woo-j/OkapiBarcode
