### ISSUE TITLE
tests fail (24 of 170)

### ISSUE THREAD

**Issue by FauthD** [woo-j/OkapiBarcode#32]
Hello,
trying to build Okapi I experience errors on 24 tests.
I tried with java 8 and 7 on 2 different machines.
The first error looks like some scaling issue:
`uk.org.okapibarcode.output.SvgRendererTest > testCode93Magnification FAILED
    org.junit.ComparisonFailure: Line 4 expected:<<svg width="2[46" height="11]0" version="1.1" xml...> but was:<<svg width="2[56" height="12]0" version="1.1" xml...>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at uk.org.okapibarcode.output.SvgRendererTest.test(SvgRendererTest.java:105)
        at uk.org.okapibarcode.output.SvgRendererTest.testCode93Magnification(SvgRendererTest.java:58)`
Note the width is 56 but expected 46, height is 12 but expected 11.

The next is a wrong bounding box followed by wrong pixels. Could well be same root cause.

Host machine is Ubuntu 14.04. Perhaps this is the issue? How do you guys build? On Windows?
Thanks a million, Dieter Fauth

**Comment by A024806** [comment]
2016年6月11日 23:09於 "FauthD" <notifications@github.com>寫道：

**Comment by gredler** [comment]
I'll have a look this week. I think the renderer implementations were changed without making the corresponding changes in the tests.

**Comment by gredler** [comment]
Tests work for me again. I'd like to get a build set up on Travis CI so that we have a common baseline, hopefully will get that done this week.

I'm leaving this open until we get that CI build configured.

**Comment by gredler** [comment]
Haven't been able to get a build going on Travis CI for this official repo yet, but I do have one up and running on my own fork, and all the tests are passing:

https://travis-ci.org/gredler/OkapiBarcode

@FauthD can you verify that the latest code builds on your system?

**Comment by gredler** [comment]
Official Travis CI build now up and running (and passing):

https://travis-ci.org/woo-j/OkapiBarcode
