### ISSUE TITLE
Code128 Class issue

### ISSUE THREAD

**Issue by Jonney3099** [woo-j/OkapiBarcode#36]
1. Should we register All info of AIs for input verification?
2. What is readerInit in Code128 class? 
3. When I test string "c" + '\n' + "aDEF" , Code128 Class returns:
|START B|c|Shift|Chr(10)|SHIFT|a|D|E|F|CheckDigit|STOP|
There're two SHIFT,the last SHIFT is redundant. Scanner returns wrong result.

**Comment by Jonney3099** [comment]
I think there's a logic defect : 
`for (i = 1; i < sourcelen; i++) {
            last_mode = mode;
            mode = findSubset(inputData[i]);
            if((inputDataType == DataType.GS1) && inputData[i] == '[') {
                mode = Mode.ABORC;
            }
            if((modeCSupression) && (mode == Mode.ABORC)) {
                mode = Mode.AORB;
            }
            if (mode == last_mode) {
                mode_length[index_point]++;
            } else {
                index_point++;
                mode_type[index_point] = mode;  //----> **HERE!!!**, if previous Char is using SHIFT, the next char can't be SHIFT any more. 
                mode_length[index_point] = 1;
            }
        }`

**Comment by gredler** [comment]
Fixed.
