### ISSUE TITLE
ExtendedOutputStreamWriter uses locale specific format for double

### ISSUE THREAD

**Issue by martinsefcik** [woo-j/OkapiBarcode#37]
```ExtendedOutputStreamWriter``` uses system locale specific format for formatting double values and then at least rendered SVG (I didn't try other output formats) is not readable in case if system locale uses comma instead of dot as decimal separator.

Example of invalid SVG with commas (not readable by many SVG viewers/edtiors):
```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
   "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="27" height="50" version="1.1" xmlns="http://www.w3.org/2000/svg">
   <desc>5</desc>
   <g id="barcode" fill="#000000">
      <rect x="0" y="0" width="27" height="50" fill="#FFFFFF" />
      <rect x="0,00" y="0,00" width="1,00" height="40,00" />
      <rect x="2,00" y="0,00" width="1,00" height="40,00" />
      <rect x="4,00" y="0,00" width="1,00" height="40,00" />
      <rect x="8,00" y="0,00" width="1,00" height="40,00" />
      <rect x="10,00" y="0,00" width="3,00" height="40,00" />
      <rect x="16,00" y="0,00" width="3,00" height="40,00" />
      <rect x="20,00" y="0,00" width="1,00" height="40,00" />
      <rect x="22,00" y="0,00" width="3,00" height="40,00" />
      <rect x="26,00" y="0,00" width="1,00" height="40,00" />
      <text x="13,00" y="48,00" text-anchor="middle"
         font-family="Helvetica" font-size="8,00" fill="000000">
         05
      </text>
   </g>
</svg>
```

Not very nice workaround:
```java
  Locale systemLocale = Locale.getDefault();
  Locale.setDefault(Locale.ROOT);
  SvgRenderer barcodeRenderer = new SvgRenderer(os, 4, 5, Color.WHITE, Color.BLACK);
  barcodeRenderer.render(barcode);
  Locale.setDefault(systemLocale);
```

**Comment by gredler** [comment]
We use the the `append(double)` method in both the PostScript renderer and the SVG renderer. It appears that both should always use periods as decimal separators.

[Mozilla Developer Network: SVG Content Types](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#Number)

> number ::= integer | [+-]? [0-9]* "." [0-9]+

[PostScript Language Reference, 3rd edition](https://www.adobe.com/products/postscript/pdfs/PLRM.pdf)

> A real number consists of an optional sign and one or more decimal digits, with an embedded period (decimal point), a trailing exponent, or both. The exponent, if present, consists  of  the  letter E or e followed  by  an  optional  sign  and  one  or more decimal digits. The number is interpreted as a real number and is converted to  a  real  (floating-point) object. If it exceeds the implementation limit for real numbers, a limitcheck error occurs.
