### ISSUE TITLE
Gradlew test errors from multiple linux

### ISSUE THREAD

**Issue by lamjtme2** [woo-j/OkapiBarcode#44]
Hi,
I'm getting test errors from "gradlew check" on the following combinations.

These come back with "187 tests completed, 45 failed":
  CentOS 6.8 - OpenJDK Runtime Environment (rhel-2.6.9.0.el6_8-x86_64 u131-b00)
  CentOS 7.3 - OpenJDK Runtime Environment (build 1.8.0_121-b13)
  Ubuntu 15.10 - OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~15.10.1-b14)

These come back with "179 tests completed, 163 failed":
  Windows 10 Pro - Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

Just when I'm about to give up, this compiles correctly!
  - MacOS Sierra v10.12.3 - Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
  
Are you guys aware of any problems in the CentOS or OpenJDK environment?

**Comment by gredler** [comment]
I don't think the tests will pass on OpenJDK, because the 2D graphics subsystems are different in OpenJDK and the Oracle JDK and therefore generate slightly different outputs.

I am surprised however that the tests failed on Win10 + Oracle JDK. That *was* Oracle JDK that you used on Windows 10, correct?

**Comment by lamjtme2** [comment]
Thanks for the hint.  These platforms are compiling correctly now:
  Ubuntu 15.10 - OracleJDK 1.8.0u121
  CentOS6.8 - OracleJDK 1.8.0u121
  CentOS7.3 - OracleJDK 1.8.0u121
  
I was using OracleJDK on my Win10Pro.  Completely uninstalled and reinstalled OracleJDK 1.8.0u121.  Same 163 test errors, unfortunately still broken.
  java version "1.8.0_121"
  Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Attaching gradlew output w/ debugging enabled and report.
[index.zip](https://github.com/woo-j/OkapiBarcode/files/836102/index.zip)
[dump-gradlew.txt](https://github.com/woo-j/OkapiBarcode/files/836103/dump-gradlew.txt)

**Comment by gredler** [comment]
Thanks for the research!

I've added a note to the README about the difference between Oracle JDK and OpenJDK when running the tests.

I suspect that your line endings aren't being converted from \n to \r\n when pulling from Git to Windows, which is messing up the loading and parsing of the test input and expectation files at runtime.

https://help.github.com/articles/dealing-with-line-endings/
https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by lamjtme2** [comment]
Yep, it was the line endings when using the Zip download that hosed the Windows build.  I set my local git configuration with:

git config --global core.autocrlf true

and then re-cloned the respository.  More than half the files in the repository (including EPS, SVG and some java files but not all) are affected by this.  Thanks for the help!
