### ISSUE TITLE
Wrong error message on setContent when Symbol.DataType.GS1

### ISSUE THREAD

**Issue by schuster-rainer** [woo-j/OkapiBarcode#52]
The following line returns "no input data" which is wrong behaviour.

The gs1SanityCheck sets the error_msg to the actual error message and returns "".  I figure this out while setting the content to "[01]123456789" which should resolve into a "Invalid data length for AI". This is true for all errors with gs1

https://github.com/woo-j/OkapiBarcode/blob/b30b61bb5aec9240d774d81330186b2d389206f8/src/main/java/uk/org/okapibarcode/backend/Symbol.java#L389

**Comment by gredler** [comment]
Thanks for the bug report, this should be fixed now.
