### ISSUE TITLE
QUESTION: MaxiCode for UPS

### ISSUE THREAD

**Issue by Kirbylix** [woo-j/OkapiBarcode#53]
Good day,
I am trying to generate a MaxiCode for the parcel delivery UPS with your program. Here it is not really clear to me how their formatting for the primary and secondary value range are. The code should be generated in mode 3 and should show the following example when reading:

> (Ship-To Postal Code) 1023 
> (Ship-To Country Code) 756
> (Class of Service) 068
> (Tracking Number) 1Z95456724
> (SCAC) UPSN
> (Shipper Number) 0A4190
> (Julian Day of Pickup) 231
> (Shipment ID Number) 
> (Package In Shipment) 1/1
> (Weight in pounds) 3
> (Address Validation) N
> (Ship-To Address) 
> (Ship-To City) BASEL
> (Ship-To State)

I thank you already once for the help
Many greetings

**Comment by gredler** [comment]
I'm not familiar with the UPS rules. This looks like a good resource:

https://www.neodynamic.com/Products/Help/BarcodeWP1.0/barcodes/MaxiCode.htm
