### ISSUE TITLE
Width of Ean and Upc barcodes

### ISSUE THREAD

**Issue by ArvJak** [woo-j/OkapiBarcode#54]
Good day,
I am trying to generate EAN and UPC barcodes.
According to GS1 specification width of the symbol must be controlled using x-dimension.
Do we also follow the same?
If yes, how to pass the values of x-dimension (magnification factor).
If no, how do we manage width of the symbols.

My findings:
Symbol class has "moduleWidth" as one of the parameters, but this is not considered while creating EAN/UPC symbols. (symbol class plot method uses "moduleWidth").

Thanks in advance.

**Comment by gredler** [comment]
Regarding taking the moduleWidth into account: this may be useful after all, so I've added it to the code (will be available in the next release).
