### ISSUE TITLE
QRCode: How can I use Numeric or Binary Encoding

### ISSUE THREAD

**Issue by andrm** [woo-j/OkapiBarcode#55]
Thanks for this great library!

I'm trying to use QRCode and I wonder how I can use the numeric or binary encoding. Using setContent("1234") did not work, I'm getting "TEXT" in the Zxing app.

**Comment by gredler** [comment]
Glad you are finding it useful! The library automatically chooses the encoding method based on internal optimizations (see the logic in the [QrCode](https://github.com/woo-j/OkapiBarcode/blob/master/src/main/java/uk/org/okapibarcode/backend/QrCode.java) class). Is there a reason you care about the encoding chosen?

**Comment by andrm** [comment]
The reason is that numeric encoding is very efficient and I have a use case that all the information is only numeric. I did try to send a string only with numeric literals ("12345") with OkapiBarCode and the BarcodeScanner on Android displays the type as "TEXT" which prompted me to ask this question.

What I would like from the library is a mode where I can send only a number, not a string so the library knows that it should encode it as numeric. Does that make sense?

**Comment by gredler** [comment]
Do you have an example where the content would fit into a symbol of a specific size if it were encoded as numeric data, but does not fit because it is not encoded as numeric data?

**Comment by andrm** [comment]
Not important for me right now.
