### ISSUE TITLE
UPNQR support

### ISSUE THREAD

**Issue by jjakob** [woo-j/OkapiBarcode#57]
Hi,

Any chance of porting UPNQR from ZINT?

**Comment by gredler** [comment]
How is UPN QR different from a regular QR code?

**Comment by jjakob** [comment]
It's a different format, added recently in Zind. I don't think there's much resemblance between them.

**Comment by jjakob** [comment]
It's a different format, added recently in Zind. I don't think there's much resemblance between them.

**Comment by gredler** [comment]
UPN QR Code = standard QR Code but must be version 15 (size 77x77), must use ECC level M, must use ECI 4 (ISO-8859-2), and must use byte mode encodation.
