### ISSUE TITLE
GS1 expanded stacked creation fails

### ISSUE THREAD

**Issue by peter-fe** [woo-j/OkapiBarcode#60]
To reproduce try to render the following sequence:
[01]09120065560002[21]01052020007146460053[10]01641093740

In Zint this is done correctly.

Doing some brief debugging it seems that the [10] AI gets replaced with "\\\<FNC1>" and later on line 1061 in DataBarExpanded.java the latch gets set to true because of the added "\\" from "\\\<FNC1>" at line 1104 it finally fails with throwing an "Invalid characters in input data"

**Comment by gredler** [comment]
Thanks for the bug report. I can replicate on my end, and will take a deeper look soon. The GS1 DataBar variants haven't received the same level of testing as most of the other symbologies, so I'm not too surprised...

**Comment by peter-fe** [comment]
Hi Daniel,

Thank you for looking that up, pls let us know if we can assist you in any way to get this fixed e.g.: testing or providing additional samples.

best
Peter

**Comment by awenger** [comment]
Hi @gredler , did you find already some time to look into this problem? I stumbled upon the same problem today.

**Comment by gredler** [comment]
Can you guys give it another try? Everything appears to be working on my end now. Thanks!

**Comment by awenger** [comment]
thanks! Works also for me now

**Comment by peter-fe** [comment]
Works for me as well, big thank you for fixing this!
