### ISSUE TITLE
Color barcode support

### ISSUE THREAD

**Issue by DonaldTsang** [woo-j/OkapiBarcode#67]
Sorry for asking, does this repo has color barcode support?
- https://github.com/jabcode/jabcode
- https://github.com/ouyangzhibo/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes

**Comment by gredler** [comment]
We support custom ink and paper output colors (usually ink=black and paper=white), but we do not support the JAB Code or HiQ barcode formats.
