### ISSUE TITLE
Error when encode Unicode for Aztect 2D barcode

### ISSUE THREAD

**Issue by locht710** [woo-j/OkapiBarcode#70]
I have a string data
`"[)>\u001E01\u001D02\u001D10700\u001D203\u001D329\u001D0000000933\u001DGEOP\u001Ddadq\u001D347\u001Dre1\u001D001/001\u001D99.99KG\u001DN\u001DŽŒÇčË\u001DRW\u001D\u001DR\u001D\u001E07\u001DG03\u001D0\u001D0\u001D1\u001DRa\u001FR\u001FHOÀNG TRỌNG LỘC\u001F+333\u001F\u001F+222\u001FRlocht710@gmail.com\u001FR1\u001FR\u001FR\u001DB\u001D99.99KG\u001D12\u001D12\u001D\u001D\u001D\u001D\u001D\u001D1\u001D\u001D\u001E07\u001DS010\u001D\u001F+301212\u001F12\u001F1\u001FK2-C\u001F\u001FHa Noi\u001F10700\u001F203\u001D\u001E07\u001DS020\u001DCHF\u001D100.00\u001D0\u001D\u001E\u0004"`
I want to generate the Aztec barcode as follow: 
```
uk.org.okapibarcode.backend.AztecCode aztecCode = new uk.org.okapibarcode.backend.AztecCode();
aztecCode.setContent(data);
```
But when reading the barcode, the string is broken with a lot of strange symbols and characters.
Could you point out to me the problems? How can I create the Aztec barcode for string with Unicode characters?

Thank you so much.

**Comment by gredler** [comment]
I see you closed this issue. Did you find the problem?

**Comment by locht710** [comment]
I am not sure. I installed a lot of barcode apps on google play to read the Aztec code. Most of the apps (I think they use zxing library) output the broken string. Just one from Accusoft returns the exact result. Maybe two libraries are not compatible?
