### ISSUE TITLE
LibreOffice integration

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [woo-j/OkapiBarcode#71]
Since LibreOffice supported Java, and LibreOffice allowed to works with oher JVMs as AdoptOpenJDK and Amazon Corretto, it’s possible to create an extension to insert barcodes directly into document, and give more advanced controls to the user.

Some documentations available at https://wiki.documentfoundation.org/Development/Extension_Development

**Comment by gredler** [comment]
This is not something I'm likely to work on myself, but might accept a PR. This might be better as a separate project that uses Okapi internally, though?

**Comment by gredler** [comment]
Better if this were a separate project with a dependency on this library.
