### ISSUE TITLE
[SEC] Update Dependencies to jCommander 1.80

### ISSUE THREAD

**Issue by coding-jj** [woo-j/OkapiBarcode#78]
Please Update to jCommander 1.80 because of Security Issue [WS-2019-0490](https://www.whitesourcesoftware.com/vulnerability-database/WS-2019-0490) in jCommander.

jCommander 1.80 is only available via jCentral [MVN Repository - com.beust.jcommander](https://mvnrepository.com/artifact/com.beust/jcommander?repo=jcenter)

**Comment by gredler** [comment]
Thanks for the heads up. We'll probably upgrade to 1.78, which is on central and also contains the fix. Based on past experience, my assumption is that 1.80 will also make it to Maven central eventually.
