### ISSUE TITLE
Datamatrix cannot add HumanReadableText

### ISSUE THREAD

**Issue by himadri-mandal** [woo-j/OkapiBarcode#79]
Datamatrix removes readable, I think we do need human-readable here similar to other symbols.

https://github.com/woo-j/OkapiBarcode/blob/62416512b99c1a938e164b809066537da8c4a30f/src/main/java/uk/org/okapibarcode/backend/DataMatrix.java#L432

**Comment by gredler** [comment]
There's not a lot of precedent for this, e.g. barcode4j [never displays](http://barcode4j.sourceforge.net/trunk/symbol-datamatrix.html) human-readable text for Data Matrix symbols, same for zint (at least via the GUI).

The spec (ISO/IEC 16022) seems to discourage it, but leaves the door open to "descriptive text" in Section 10.1:

> Because Data Matrix symbols are capable of encoding thousands of characters, a human readable interpretation of the data characters may not be practical. As an alternative, descriptive text rather than the encoded text may accompany the symbol.

I'd be glad to review a PR, but any change should fit nicely in the existing framework and not change the default behavior (no human readable text).

**Comment by gredler** [comment]
Closing for now, feel free to reopen if you have additional information or a sample implementation.
