### ISSUE TITLE
ECI Support

### ISSUE THREAD

**Issue by woo-j** [woo-j/OkapiBarcode#8]
Add ECI support to extend encoding beyond Latin-1. Relates to numerous symbologies.

**Comment by woo-j** [comment]
Now completed, ECI support allows encoding in ISO 8859-1 through 8859-16, Windows 1250 through 1252 and 1256, Shift-JIS and UTF-8.

**Comment by Jonney3099** [comment]
Regarding ECI:
Very careful that Shift-JIS can Encode partial Chinese so we need to check whether SignificantByte is beyond Shift-JIS after encodation:
0x81 to 0x9F ,0xE0 to 0xEE

I give a sample String in Chinese : " 世界是美好的。"
