### ISSUE TITLE
empty data fields in GS1 Data Matrix valid?

### ISSUE THREAD

**Issue by me-like-cookies** [woo-j/OkapiBarcode#83]
Hi,

for a test with GS1 Data Matrix, I wanted to create a GS1 Data Matrix Code with an intentionally empty data field for e.g. AI 92.
From my understanding, this site here
https://www.gs1.org/standards/barcodes/application-identifiers/92?lang=en
claims the AI and according data field need to comply a regular expression ^92[validchars]{0,90}$

I think this alleges, that ^92$, i.e. zero chars after AI 92, complies with the reg. exp. they claim to be GS1 spec.

However GS1 verification Gs1.verify() in OkapiBarcode
https://github.com/woo-j/OkapiBarcode/blob/master/src/main/java/uk/org/okapibarcode/util/Gs1.java
in L158-L163 does throw an OkapiEception "Empty data field in input data" when I call Okapi's DataMatrix.setContent("[92]"), i.e. with data field 92 of length 0.

In my understanding https://www.gs1.org/standards/barcodes/application-identifiers claims not only for AI 92 but for a total of 82 different AI by their alleged reg. exp. an explicit permit of data field length 0.

I'm not sure whether that website gs1.org really precisely quotes the actual GS1 standard and whether I'm really reading that {0,n} correctly. At least, I read the latter "somewhere on the internet": https://stackoverflow.com/questions/5034948/regex-for-a-string-of-length-0-2

Please let me know your thoughts, whether or not you think there is a mismatch of actual spec. an okapi implementation.

kind regards
M

**Comment by gredler** [comment]
I wouldn't be surprised if we should be allowing 0 length data in some cases here. I'll try to take a look soon.

**Comment by me-like-cookies** [comment]
Ok, thank you very much for putting this to consideration. 

Just a thought:
When I wrote some test code for GS1 support in our scanner message interpreter, I semi-automatically converted this page
https://www.gs1.org/standards/barcodes/application-identifiers
(advanced view of all entries) to some Java Code. So there is a mapping of AI and according reg. exp.
With this, calling Java's 
`Pattern.compile(regexp).matcher(ai + value).find()`
can test whether the value complies the reg.exp. claimed by the webpage, including length and character restrictions
