### ISSUE TITLE
Provide a method to get only the encoded value

### ISSUE THREAD

**Issue by ignatij** [woo-j/OkapiBarcode#90]
I need only the Code 128 encoded part instead of the whole image. Is there an option for this to be added?

**Comment by gredler** [comment]
What is the "encoded part"? You don't have to use a `SymbolRenderer` on the `Symbol` instance, if you just want to `setContent( )` on the symbol and then use the bar info from `getRectangles( )` directly.

**Comment by ignatij** [comment]
I need only the encoding part, for example we have the text “Hello World!”. The Code-128 encoding of this text would be: ÌHello World!WÎ
Is this possible to be exposed by your API?
Many thanks and regards.

**Comment by gredler** [comment]
I don't think we can provide what you are looking for, though I'm also not sure where you got `ÌHello World!WÎ` from?

**Comment by gredler** [comment]
This looks like a Libre Barcode font-specific string encoding, not part of a general Code 128 concept, so not something that we will address in Okapi.
