### ISSUE TITLE
PDF417: Binary data / automated structured append

### ISSUE THREAD

**Issue by uwolfer** [woo-j/OkapiBarcode#91]
1. Is there a way to pass in binary data instead of a string (I have only seen `setContent(String)` in public API)? I was not able to find any public API for setting binary data. There seems to be some internal logic for deciding if it is binary content.
2. Is there a way to handle structured append into multiple symbols (macro mode) automatically (meaning, if I pass in too much data for one 417 symbol, it will split it automatically into as many as required, and `getStructuredAppendTotal` would return the number of symbols)? I've seen methods like `setStructuredAppendPosition` which seem to handle manual append (multiple symbols). If there is no automated way, how can I split it up in an optimal way into multiple code (filling up every code as much as possible)?

**Comment by gredler** [comment]
In order to pass binary data, I'd recommend trying to use a string that uses byte escape sequences (i.e. "\xNN" = 0xNN, for example "\x00" = 0x00, "\x6B" = 0x6B, "\xFF" = 0xFF). See `uk.org.okapibarcode.util.Strings` for more information about the escape sequences supported.

There's currently no automated way to split the data and generate multiple symbols that use structured append. The only option that I can think of currently is a trial & error / iterative approach. You can probably keep the iteration fast if you use a binary search type of approach.

**Comment by uwolfer** [comment]
@gredler Thanks for your support!

> In order to pass binary data, I'd recommend trying to use a string that uses byte escape sequences (i.e. "\xNN" = 0xNN, for example "\x00" = 0x00, "\x6B" = 0x6B, "\xFF" = 0xFF). See uk.org.okapibarcode.util.Strings for more information about the escape sequences supported.

I've tried to pass a string like `\x78\xDA\xED` into `setContent`, but it looks like it still gets encoded as plain text into the symbol. What do I miss?

**Comment by gredler** [comment]
Have a look at createBlocks(int[]) and chooseMode(int). Basically 0x78 is ASCII 'x', so it decides that the best way to encode those 3 bytes is to use TEXT mode for the first byte, and BYTE mode for the next 2 bytes. I can imagine adding an option to force the usage of BYTE for the entire data string. What is your use case where the current TEXT mode + BYTE mode combination is problematic?

**Comment by uwolfer** [comment]
I think it would be nice if there would be an option to force encoding. I've looked into the mentioned methods some weeks ago, but was not able to change the encoding to binary with any input I have tried.

My use case: the Swiss e-tax return uses PDF 417 barcodes on the last pages for processing. The current reference implementation uses a proprietary library for generating these barcodes. I have tried to replace the ingratiation 1:1 (there are different applications which process these barcodes after, and I do not want to risk to break any of them), and the current impl forces binary encoding (it compresses XML text with ZIP, and then puts that ZIP binary data into the barcode). See also [this document on page 26](https://www.ech.ch/de/dokument/6bf7fcca-2714-48f9-8849-1221db1f73ee).

**Comment by gredler** [comment]
Thanks for the additional detail. Note that there seems to be [a slightly newer specification](https://www.ech.ch/index.php/de/dokument/f4501424-7781-4215-b8f9-d294cb906da2), though none of the key details appear to differ.

In theory there should be no issues caused by the specific encoding chosen, so I'd like to email the specification authors to get their feedback. In general we're trying very hard to add only necessary features, so I think it's worth the extra check before jumping into implementation. It looks like a signed XML file is supposed to be fed into the compression + barcode encoding process... do you have a sample signed XML file that we could use to illustrate the question in the email? (Ideally with realistic-but-not-real data, to avoid any PII issues.) If you can provide the signed XML file, I can take care of the rest.

**Comment by uwolfer** [comment]
> Thanks for the additional detail. Note that there seems to be a slightly newer specification, though none of the key details appear to differ.

You are right, I've linked an outdated version. The newer version contains some spec changes in the content, but not really in the technical implementation if I remember correctly.

> In theory there should be no issues caused by the specific encoding chosen

Good to know - I do not know that much about the handling of such barcodes. I've just checked out the reference implementation for the barcode reading, which can be found on your [linked document on page 31](https://www.ech.ch/index.php/de/dokument/f4501424-7781-4215-b8f9-d294cb906da2):
```java
  PDF417Reader reader = new PDF417Reader ();
  PDF417Data[] data = reader.read (new RImage (image));
```
This does not specify any encoding. Do you have any idea if `data` is the same, independent which encoding was used for creating the barcode?

> do you have a sample signed XML file

So far, I have not used any signed XML - the spec also works in my understanding without signing the XML.

> If you can provide the signed XML file, I can take care of the rest.

Thanks for your support! I can talk the the relevant people as I am connected to one of the developers, but before doing so I would like to hear your opinion about the question above.

**Comment by gredler** [comment]
> I've just checked out the reference implementation for the barcode reading

Ah, good catch. I hadn't seen that section.

> This does not specify any encoding. Do you have any idea if data is the same, independent which encoding was used for creating the barcode?

Hard to be sure, since I'm not familiar with the J4L libraries (and there's not a lot of `PDF417Reader` / `PDF417Data` documentation online), but I think it's very possible, since they simply call `data.getValue()` to get the encoded information (no other configuration or options specified).

> I can talk the the relevant people as I am connected to one of the developers

Sounds good, please let me know what they say.

If they're still updating the spec regularly, they may want to consider using open source libraries for the barcode encoding and decoding to make things more accessible (like they did e.g. by using PDFBox for the PDF file manipulation). Of course I'm partial to Okapi for barcode encoding, and there is also ZXing for decoding.

**Comment by uwolfer** [comment]
I've played around with the demo implementation, and I'm now at least able to test the barcode reading of a barcode generated with OkapiBarcode. I get the data out of the barcode, and it is exactly the same string as I've passed into `Pdf417`.

In the reference implementation, they pass the binary data into the barcode generator as it has been generated by the zip `Deflater`. Since Pdf417 requires a string for `setContent`, I've tried different things, like encoding the binary data to a HEX string. Do you have any ideas what type / format of data I could try to pass into `Pdf417` in order to get the binary data out with barcode reader?

**Comment by gredler** [comment]
Thanks for the update. Have you tried the following?

```
byte[] bytes = { 0x78, (byte) 0xDA, (byte) 0xED }; // would come from deflater usually
StringBuilder data = new StringBuilder(bytes.length * 4);
for (int i = 0; i < bytes.length; i++) {
    String hex = String.format("%02X", bytes[i] & 0xFF);
    data.append("\\x").append(hex);
}

Pdf417 barcode = new Pdf417();
barcode.setContent(data.toString());
```

**Comment by uwolfer** [comment]
> But you should be able to convert the byte[] into the necessary data string using ISO-8859-1 encoding.

Great work. That does the job! I'm able to decode the barcode generated that way. :) Thank you very much for your support.

Do you think it would make sense to extend your docs or examples? It could probably also help others.

I would like to keep this issue open for now, because as a next step, I will look into the second part of my initial request.

In addition, I have seen that the reference code sets `PDFMacroFileName`, but I have not found an equivalent like `setStructuredAppendFileName` in OkapiBarcode yet (I have seen that for example `setStructuredAppendFileId` is available, which is a different thing, and also required in this use case). Did I miss something, or is this not supported yet?

**Comment by gredler** [comment]
> Do you think it would make sense to extend your docs or examples? It could probably also help others.

Maybe, I'm just not sure where that might go. Perhaps an extra sentence in the `setContent(String)` JavaDoc? Did you read the JavaDoc yourself when trying to figure it out? Not sure how many people are using it.

> Did I miss something, or is this not supported yet?

That's correct, Okapi doesn't support any of the optional information in the Macro PDF417 Control Block (file name, segment count, timestamp, sender, addressee, file size, checksum). Does the Swiss e-tax return depend on this information being available?

**Comment by uwolfer** [comment]
> Did you read the JavaDoc yourself when trying to figure it out? Not sure how many people are using it.

I did, and even looked quite some time into the implementation in order to understand what is possible. I was not able to figure it out by myself. IMO it would make sense to add it to `setContent`.

> Okapi doesn't support any of the optional information in the Macro PDF417 Control Block (file name, segment count, timestamp, sender, addressee, file size, checksum). Does the Swiss e-tax return depend on this information being available?

It requires this information, see the spec on page 23 (translated by me):
> For unique identification during scanning the metadata contains the ID (see chapter 3.2) in the PDFMacroFileName attribute and a random number (4 integers) in the PDFMacroFileId attribute. The metadata must be supplied as a separate attribute so that it can be used even if the even if decompressing the rest of the contents fails.

Also note that `PDFMacroFileId` is only supported up to 3 digits with Okapi, but I assume this should not be an issue because this is a random number.

**Comment by gredler** [comment]
For setting binary content, I think I may just add a `setContent(byte[])` method to the `Pdf417` class. I'll also look at adding support for the file name and segment count optional fields. However, it will be a few weeks before I'm able to look at this again.

**Comment by uwolfer** [comment]
> For setting binary content, I think I may just add a `setContent(byte[])` method to the `Pdf417` class.

That sounds like a good idea to me.

> I'll also look at adding support for the file name and segment count optional fields.

Thank you!

**Comment by gredler** [comment]
@uwolfer I have a patch ready for the file name and segment count support, but no reader to test with and no control sample to compare against. Do you have either a scanner or a control sample that could be used to verify the implementation?

**Comment by uwolfer** [comment]
> I have a patch ready for the file name and segment count support

Great news! Thanks.

> ..., but no reader to test with and no control sample to compare against. Do you have either a scanner or a control sample that could be used to verify the implementation?

I have an application which is able to scan such code including that metadata. It is an application based on the specs from the PDFs linked above. If you can share the patch, or a snapshot build, I could try to integrate it into my code, and then try the generated barcode against that scanner application. The application uses `com.java4less.vision.pdf417.PDF417Reader` for reading the barcode.

As an alternative, you could also share a barcode which contains these fields, and I can try to scan it with my test application (content of the barcode would not really matter).

**Comment by gredler** [comment]
Great, here are some sample test files.

```
mode=NORMAL
structuredAppendFileId=123
structuredAppendPosition=1
structuredAppendTotal=2
structuredAppendFileName=name.txt
structuredAppendIncludeSegmentCount=true
content=this is 
```

![normal-structured-append-with-optional-fields-1-of-2](https://user-images.githubusercontent.com/178883/178737420-558a42a2-06b2-45d0-8f93-6d3e3f4bd736.png)

```
mode=NORMAL
structuredAppendFileId=123
structuredAppendPosition=2
structuredAppendTotal=2
structuredAppendFileName=name.txt
structuredAppendIncludeSegmentCount=true
content=a test
```

![normal-structured-append-with-optional-fields-2-of-2](https://user-images.githubusercontent.com/178883/178737573-1e846bb7-f53a-4a8f-bc45-cec2a137e5e7.png)

**Comment by gredler** [comment]
Yes, it looks like this will require some debugging:

**Segment index:** both are correct (`0` and `1`)
**Segment count:** should be `2` in both cases, so **first value is incorrect**, second value is correct
**Segment file ID:** both are correct (`123`)
**Segment file name:** should be `name.txt`, so **both are incorrect**
**Data:** both are correct (`this is `, `a test`)

**Comment by uwolfer** [comment]
I've spent some time debugging into the library, but I was not able to spot the issue yet. Specifically, I tried to find why the content "this is" is used as file name. To me, it really looks like this content is also in the code words.

But good news: I was able to set up a scanner with sources which can be found online. Steps:
1. download `Download J4L PDF417 Vision for Java` from here: http://www.java4less.com/vision/vision.php?info=download
2. extract the archive, import in into your IDE
3. adjust the code in `Sample.java` as follows:

Add this line in early the main method (otherwise your sample images cannot be read):
`System.getProperties().setProperty("com.java4less.vision.maxarea", String.valueOf(90000));`

Point to your test images:
`private String[] testSet = ...`

This way, you hopefully should also be able to debug your barcode. The output of this sample displays all the information. Please let me know if you have issues setting this up, or if you need any other information from me.

**Comment by gredler** [comment]
@uwolfer I was able to replicate the issue with the latest version of ZXing, which added support for reading this extra Macro PDF417 metadata. Please see the final two test images here (same inputs, same expectations):

https://github.com/woo-j/OkapiBarcode/blob/master/src/test/resources/uk/org/okapibarcode/backend/pdf417/normal-structured-append-with-optional-fields-1-of-2.png

https://github.com/woo-j/OkapiBarcode/blob/master/src/test/resources/uk/org/okapibarcode/backend/pdf417/normal-structured-append-with-optional-fields-2-of-2.png

Can you verify that these scan correctly on your end as well?

**Comment by uwolfer** [comment]
> Can you verify that these scan correctly on your end as well?

Awesome - it worked as expected with the test images. I have not tested your code yet. Thank you so much for your work on this - really appreciated.

Regarding my initial request, point 2 ("automated append"): Do you think it would also make sense to cover this in Okapi, since you now fully support segments? Otherwise I will try your approach in my code.

**Comment by gredler** [comment]
Great! Thanks for checking. I've created #92 to track the "automated append" feature request separately. It's not going to be a priority right now for me, but I'd be happy to review a pull request. From a user API perspective, it could be as simple as a new `public static List<Pdf417> createStructuredAppendSymbols(String content, Pdf417 template)`, or it could look differently if you have a better idea.

**Comment by uwolfer** [comment]
I am not sure if this is the right place to report it, but as it is related to binary data encoding, I'll add it here for now.

I have noticed an encoding issue with one specific character: \` (hex encoded `60`) gets encoded in the barcode into `?` (hex `3f`)

Input:
![Screenshot_20220818_105445](https://user-images.githubusercontent.com/2202/185354224-02cfa6a9-d7b5-48af-94d1-89eaa3b18d7a.png)

Content after reading the barcode:
![Screenshot_20220818_105529](https://user-images.githubusercontent.com/2202/185354354-d6d2981a-6c9c-45ac-814b-b1fab41cd6a9.png)

Is the information already useful? Or do you need more context?

**Comment by uwolfer** [comment]
I am not sure if this is the right place to report it, but as it is related to binary data encoding, I'll add it here for now.

I have noticed an encoding issue with one specific character: \` (hex `60`) gets encoded in the barcode into `?` (hex `3f`).

Edit: I cannot reproduce this issue with ZXing as used in your test cases, but I'm able to reproduce this issue with "J4L Barcode Vision" for example. You can reproduce the issue with these symbols:

Generated with Okapi:
![oki](https://user-images.githubusercontent.com/2202/185383675-0e41d0e5-aa31-4852-85d6-73beed3e9c85.png)
![Screenshot_20220818_105529](https://user-images.githubusercontent.com/2202/185354354-d6d2981a-6c9c-45ac-814b-b1fab41cd6a9.png)

Generated with RBarcode (this symbol contains a few more bytes at the end):
![rbarcode](https://user-images.githubusercontent.com/2202/185383695-62bb7f2e-0516-4c78-916c-954f8fa46252.png) 
![Screenshot_20220818_105445](https://user-images.githubusercontent.com/2202/185354224-02cfa6a9-d7b5-48af-94d1-89eaa3b18d7a.png)


Is the information already useful? Or do you need more context?
