### ISSUE TITLE
RoyalMail4State is not working as expected

### ISSUE THREAD

**Issue by harikrishnaganji98** [woo-j/OkapiBarcode#93]
we are using RoyalMail4State class to generate a barcode.
Below is the implementation of the class.
public Symbol symbolInstance() {
            RoyalMail4State royalMail4State = new RoyalMail4State();
            return royalMail4State;
        }
we pass this object to other class and set the required content.
and using below logic to generate Image.

BufferedImage image = new BufferedImage(params.realWidth, params.realHeight, BufferedImage.TYPE_BYTE_GRAY);
        Graphics2D g2d = image.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        Java2DRenderer renderer = new Java2DRenderer(g2d, params.factor * MAGNIFICATION_FACT, Color.WHITE, Color.BLACK);
        renderer.render(symbol);

Barcode generated from Okapi Lib
<img width="561" alt="Screenshot 2022-07-05 at 12 49 48 PM" src="https://user-images.githubusercontent.com/53658356/180164461-f98bdc9b-3c76-4c7b-8ce4-3a5b95787b92.png">
Barcode Generated from online suorce
![RM4SCCcode](https://user-images.githubusercontent.com/53658356/180164557-f5010c23-9df3-4d62-b474-49852009f877.png)

we observe the difference is in the last few lines in the image.
please ignore height and width of those lines
cc: @gredler

**Comment by gredler** [comment]
Thanks for the detailed issue description, this does indeed look like a bug.

**Comment by gredler** [comment]
Fixed in the 0.3.3 release, which was just pushed to Maven Central.

**Comment by harikrishnaganji98** [comment]
Thank you @gredler
