### ISSUE TITLE
EAN13: first number get cut of

### ISSUE THREAD

**Issue by AntonLiashenka** [woo-j/OkapiBarcode#99]
I'm not able to render EAN13 with first number:

For input: **123456789123** it is rendered as:

<img width="117" alt="image" src="https://github.com/woo-j/OkapiBarcode/assets/1217820/aa5a09ca-8593-4074-b10d-4492c2715a39">

I'm expecting barcode rendered as:
<img width="265" alt="image" src="https://github.com/woo-j/OkapiBarcode/assets/1217820/e4ecd487-7262-4f1c-91d6-b2bad4960777">

Am I doing something wrong? missing some flags?

**Comment by gredler** [comment]
Are you clipping the drawing area somehow? The first number is added automatically, please see some of the test cases here:

https://github.com/woo-j/OkapiBarcode/tree/master/src/test/resources/uk/org/okapibarcode/backend/ean

**Comment by AntonLiashenka** [comment]
@gredler not sure about tests.. but here is a code from examples:

```
@Test
    @SneakyThrows
    public void test() {
        Ean barcode = new Ean();
        barcode.setMode(Ean.Mode.EAN13);
        barcode.setFontName("Monospaced");
        barcode.setFontSize(16);
        barcode.setModuleWidth(2);
        barcode.setBarHeight(50);
        barcode.setHumanReadableLocation(HumanReadableLocation.BOTTOM);
        barcode.setContent("123456789012");

        int width = barcode.getWidth();
        int height = barcode.getHeight();

        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_BYTE_GRAY);
        Graphics2D g2d = image.createGraphics();
        Java2DRenderer renderer = new Java2DRenderer(g2d, 1, Color.WHITE, Color.BLACK);
        renderer.render(barcode);

        ImageIO.write(image, "png", new File("ean13.png"));
    }
```
result:
![telegram-cloud-photo-size-2-5287601317361077470-m](https://github.com/woo-j/OkapiBarcode/assets/1217820/4f167e92-32c0-48ee-b527-b78b17c741e9)

library version is the latest one `0.4.0`

**Comment by gredler** [comment]
It might be drawing off-screen. Try adding a horizontal quiet zone.

**Comment by AntonLiashenka** [comment]
@gredler thanks! it helped. 
![telegram-cloud-photo-size-2-5292104916988448836-y](https://github.com/woo-j/OkapiBarcode/assets/1217820/92f87987-4b44-4a69-b1a5-7e7f5cc5778f)
![telegram-cloud-photo-size-2-5292104916988448734-x](https://github.com/woo-j/OkapiBarcode/assets/1217820/3e86f84f-5a44-4fe6-bede-475ff62a95b1)
